# Generated by Django 4.1.6 on 2023-02-16 11:11

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create',
            field=models.DateTimeField(default=base.models.EET_time),
        ),
    ]
